// <auto-generated />
namespace DonorRegister.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingisacknowlededfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingisacknowlededfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201708190350528_adding-is-acknowleded-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
